pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh """cd /var/lib/jenkins/workspace/test2/simple-java-maven-app-master
                pwd
                mvn -B -DskipTests clean package"""
            }
        }
        stage('Test') {
            steps {
                sh """cd /var/lib/jenkins/workspace/test2/simple-java-maven-app-master 
                mvn test"""
            }
            post {
                always {
                    junit """cd /var/lib/jenkins/workspace/test2/simple-java-maven-app-master 
                    target/surefire-reports/*.xml"""
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
